services:
  api:
    build: ./server
    container_name: shop-api
    ports:
      - "8081:8081"
  web:
    build: ./client
    container_name: shop-web
    depends_on:
      - api
    ports:
      - "80:80" 
