# config/routes.yaml

product_index:
  path: /product
  controller: App\Controller\ProductController::index
  methods: [GET]

product_create:
  path: /product/create
  controller: App\Controller\ProductController::create
  methods: [POST]

product_update:
  path: /product/{id}
  controller: App\Controller\ProductController::update
  methods: [PUT, PATCH]

product_delete:
  path: /product/{id}
  controller: App\Controller\ProductController::delete
  methods: [DELETE]

home:
  path: /
  controller: App\Controller\ProductController::index
  methods: [GET]
